### PR TITLE
Add Requests Cache

### PR DESCRIPTION
**Pull request by camrongodbout**
## PR Objective:
Add requests cache to nba_api to cache requests made to the public API

## What Changed:
* Added requests_cache to the setup.py
* Added requests_cache setup to the http.py file

## Technical Reasoning for Changes:
We want to cache the API requests to NBA's api to speed up multiple calls to same endpoint. To accomplish this we drop a plug and play package of `requests_cache` from https://github.com/reclosedev/requests-cache

### CODE REVIEW

**Comment by swar** [comment]
Will this affect people who do not want to cache their requests? As long as this doesn't automatically enable requests-cache for everyone, I am fine with merging. Just want to make sure the user has the option to enable and disable caching on demand.

**Comment by swar** [comment]
@camrongodbout

**Comment by camrongodbout** [comment]
It would add it to everyone by default, also what's the best method for running the package tests?

**Comment by swar** [comment]
@camrongodbout I am going to wait until I have a way of opting into this feature prior to merging it to master.

To your second question, I have been running https://github.com/swar/nba_api/blob/master/tests/stats/test_endpoints.py and then debugging issues as they come up. I haven't had any issues major issues other than small nuances here and there. This is definitely not the best way of testing it out, but it's the only thing I have set up currently because a lot of testing is also done when analyzing the endpoints using the endpoint analyzer.

**Pull request closed without merging**
