### PR TITLE
Fix/fix headers

### PR DESCRIPTION
**Pull request by danchyy**
Pull request which is handling issues #124  and #125 regarding headers and time outed connections.

Also included the fix which adds Carmelo Anthony as an active player which is mentioned in issue #105 .

### CODE REVIEW

**Comment by swar** [comment]
@danchyy 

I want to give you credit for the headers fix, but I need you to separate this with the Carmelo commit you created. There is a tool to generate the static player file and I want to avoid commits in that file that appear to have done manual edits.

**Comment by danchyy** [comment]
No problem, do you want me to update PR, or will you do the changes now during the weekend? I am already doing to workaround which you said in the issue, so it's the same for me.

**Comment by swar** [comment]
@danchyy 

Feel free to update the PR or create a new one with just the headers. I am going to update them when I make the update regardless so your call!

**Comment by gimann421** [comment]
Noob here, is it fixed? When it is done do I need to pip uninstall and pip install again?

**Comment by swar** [comment]
@gimann421 will be up shortly. You can follow those steps and it will update on your end.

**Comment by danchyy** [comment]
Thanks for adding it man, I was traveling during weekend so didn't really find time to clean up PR, great job :)

**Pull request closed without merging**
