### PR TITLE
Automate package testing with Nox

### PR DESCRIPTION
**Pull request by gw-moore**
This PR adds Nox to automate package testing.

[Nox](https://nox.readthedocs.io/en/stable/) is a command-line tool that automates testing in multiple Python environments. For each session, Nox will automatically create virtualenv with the appropriate interpreter, install the specified dependencies, and run the commands in order.

The Noxfile.py has one session to run pytest. This can be extended to included more session to preform other test, such as formatting checks. I also made a requirements.txt and edited the README.md.

### CODE REVIEW

**Comment by swar** [comment]
@gw-moore, Give me a few days or so to get to reviewing this PR. Thank you!

**Comment by swar** [comment]
I will take a look at this, this week. I have been all over the place and haven't been purposely ignoring it. 😞

**Comment by gw-moore** [comment]
No worries! No rush on my end.

**Comment by eswan18** [comment]
I spoke with @gw-moore about this. I think we agreed to table Nox integration until our testing and deployment workflow is more complex (e.g. building docs, running linters, testing multiple Python versions). At the moment, we don't yet have complicated enough needs to justify the added complexity.

@swar – I think you can probably just close this out for now and we'll come back to it when it makes more sense.

**Comment by rsforbes** [comment]
@eswan18 / @gw-moore - Would having Nox help with local testing? Since CircleCI has [prebuilt Python images](https://circleci.com/docs/2.0/circleci-images/#python), I'm not sure that Nox helps there; however, I'm wondering if it would be good to use locally? Example:

1. I use Python 3.7.3 locally
2. I create a change
3 (today). I have to commit that change...push to my repo...run circle ci...see it fail, wash, rinse, repeat.
4 (tomorrow). With Nox, I simply run it and it sets up the VirtualEnvs with the right versions of python and boom, all tests run against expected versions.

Unless of course I'm missing something significant...as I'm not familiar with Nox. :-)

**Pull request closed without merging**
