### PR TITLE
PROPOSAL: Play By Play Data

### PR DESCRIPTION
**Pull request by rsforbes**
@swar / @eswan18 - I've been doing a ton of work with playbyplay data in parsing through descriptions. I have most of the regex completed for EVENTMSGTYPEs 1 - 13 & 18. I'd like to add something like the following into the data.py library for EVENTMSGTYPE and EVENTMSGACTIONTYPE. Likely I'd create a playbyplay.py static library to go over it similar to the players.py and teams.py.

Thoughts on the structure of the data in this PR and the idea behind it?

Here are a few of the regex I've been using. I could add some of this into the tools section.

`player_turnover = re.compile("^(?!.*(:|STEAL))(?P<name>\w+(?P<char>(\. \w+)|(\-?\'?\w+))?( (?P<suffix>Jr.|Sr.|I|II|III|IV|V))? )(?P<turnover_type>[\w+?\-? ]*) (?<!Turnover )")
#Steal
steal = re.compile("^.*STEAL.*$")
#Team Turnover
team_turnover = re.compile("(?<=Turnover: ).*(?= \()")

#FREE_THROW
free_throw = re.compile("Free Throw (?P<type>(\w+ )?(\d of \d)|\w+)")

field_goal_made = re.compile('(\s{2}|\' )([\w+ ]*)')
field_goal_missed = re.compile('(\s{2}|\' )([\w+ ]*)')

#FOUL
player_foul = re.compile("^(?P<name>\w+(?P<char>(\. \w+)|(\-?\'?\w+))?( (?P<suffix>Jr\.|Sr\.|I|II|III|IV|V))? )(?P<foul_type>.*)(?=(\(\w+\d+(\.\w+[\d|\w]+)?\)))")
team_foul = re.compile("")
`

### CODE REVIEW

**Comment by eswan18** [comment]
I think this looks great and would be really handy if you implement the regex stuff above.

In the long term, I do worry a little about having static resources in case the NBA changes its API, but there may be no better way.

**Comment by rsforbes** [comment]
Agreed on the NBA changing stuff. I’ve searched through forums and discussions for any play by play enums, doesn’t seem like there’s much consistency. Thinking a regex might be a good way to validate if they do change.

**Comment by swar** [comment]
@rsforbes This is fantastic!

I think adding this data will definitely be helpful including the regex. Just need to find a way to make a test so we can test the regex's frequently so we can cover the potential issue mentioned by @eswan18 

I am guessing this would be transferable to PlayByPlayV2 as well?

**Comment by rsforbes** [comment]
@swar - 100% transferable to the PlayByPlayV2.

Also, I think I have a way to parse and then turnaround and validate for future changes. 

Essentially...

To parse turnovers like `Nance Jr. 3 Second Violation Turnover (P2.T9)` which is `EVENTMSGTYPE == 5` and `EVENTMSGACTIONTYPE = 8`  you use `^(?P<name>\w+(?P<char>(\. \w+)|(\-?'?\w+))?( (?P<suffix>Jr.|Sr.|I|II|III|IV|V))?) (?P<turnover_type>[\w+?\-? ]*) (Turnover[ ]?)+ \(P\d+\.T\d+\)`. The name aspect is why it is so long. Anyway, that produces `turnover_type = 3 Second Violation` 

You can then turn around and use the retrieved value of `3 Second Violation` to replace `[\w+?\-? ]*` which gives you the validation for the `EVENTMSGTYPE == 5` and `EVENTMSGACTIONTYPE = 8` as `^(?P<name>\w+(?P<char>(\. \w+)|(\-?'?\w+))?( (?P<suffix>Jr.|Sr.|I|II|III|IV|V))?) (?P<turnover_type>3 Second Violation) (Turnover[ ]?)+ \(P\d+\.T\d+\)`

Hence any changes can be validated in either real time or

**Comment by rsforbes** [comment]
Working on a different format for regular expressions based on feedback. :-)

**Pull request closed without merging**
