### PR TITLE
add info about nba_apiv3 package

### PR DESCRIPTION
**Pull request by shufinskiy**
@rsforbes hello.
I create package nba_apiv3 from fork nba_api. It allows you to work with API version 3, while being completely identical to the nba_api package. I would be grateful if a link to it appears in the README of main package.

### CODE REVIEW

**Comment by rsforbes** [comment]
@shufinskiy - Its timely that you created this PR. I was actually reviewing V3 endpoints today and looking at their integratio into the code base. I actually emailed @swar just the other day.

That all being said, is there a reason you aren't merging your fork? 

I don't see the value to users in having two competing Python NBA APIs; which creates all sorts of confusion for users. Think Python2 vs. Python3; both of which were active for years until they finally killed Python2.

Clearly you have a passion for the API and we'd be thrilled to have you as a maintainer. There is more work than anyone has hours in a day.

If you are interested, let's collaborate on what you have built. Let me get up to speed on your work, compare my notes on where I was headed, and work on a unified merge that keeps a unified API and community. 

What do you think?

**Comment by swar** [comment]
Just wanted to chime in here and say that I agree with Randy! We added support for V2 endpoints when they came out and we do plan to add support for V3 endpoints. As Randy mentioned, he just started a conversation about this with me today!

Looking forward to hearing back from you!

**Comment by shufinskiy** [comment]
@rsforbes @swar 
My ultimate target is to integrate version 3 endpoints into nba_api. I have no task to create a separate ecosystem, which is why my package contains only V3 classes. nba_apiv3 is an intermediate, but there are several reasons why I decided to create it:

1. Incomplete integration. If you look at the nba_api v3 code, you will see that I have made changes to the code that are invisible to the end user, but do not allow the use of new endpoints in nba_api "as is". I have a couple of ideas on how to make the code fully compatible with the nba_api codebase, but I haven't implemented them yet.

2. Time. I planned to finish everything in June, but it turned out in mid-September. I do not know when it will be possible to integrate V3 into nba_api, so I wanted to give people the opportunity to receive data now, because over the past year I have dropped the custom V3 code into slack several times.

Therefore, I am happy to accept your proposal to join forces to implement V3 in nba_api, but I think that for now it would be possible to accept my PR and give people information that they can work with these endpoints right now.

Thanks.

**Comment by swar** [comment]
@shufinskiy 

Thank you for all that you have done! Unfortunately, we cannot include a link to an external GitHub. This is primarily because we cannot validate the information within it. A link to it would mean we are advocating for it and I don't think we can do that.

**Comment by rsforbes** [comment]
@shufinskiy -  I'll pull down your repo and get started reviewing. I'm really interested to see what you've come up with and how closely it's related to what I was considering this week. 

Feel free to open up a draft PR from your fork. This will block any merges but allow github to show the proposed change set.

**Comment by rsforbes** [comment]
Closing pull request and will collaborate on merging in the fork for v3 endpoints.

**Pull request closed without merging**
