### PR TITLE
added official team colours

### PR DESCRIPTION
**Pull request by oladimeji09**
added official team colours for visualisations

### CODE REVIEW

**Comment by ChristopherBanas** [comment]
this is amazing

**Review by rsforbes — CHANGES_REQUESTED** [review]
@oladimeji09 

Thank you for your PR. Please address the requested changes:

Maintain Consistency
- The contents of data.py are maintained as dictionaries and include named indexers (e.g. team_index_id = 0, team_index_abbreviation = 1, etc.)

Include Automation for Repeatability/Maintainability
- Information within data.py is maintained via a template: [nba_api/stats/static/teams.py](https://github.com/swar/nba_api/blob/9ec5e7b631caaaca7e9bb047efbc354ef247673d/nba_api/stats/static/teams.py)
- Automation is carried out through the following script: [nba_api/tools/stats/static_players_update/update.py](https://github.com/swar/nba_api/blob/master/tools/stats/static_players_update/update.py)

Documentation/Terms of Use
- If not original work, all sources need to be identified and linked to terms of usage. (e.g. [NBA Terms of Use Statistics](https://www.nba.com/termsofuse)

Let me know if you have any questions. 

#go-pacers

**Comment by rsforbes** [comment]
@oladimeji09 - Answering your question here, for history.

Question: do you think it would be easier for me to update the teams dictionary instead of creating a new one ?

Response: This is a very good question. Anytime there is a proposed change in fundamental base data structures, it's always good to review.

First, we need to keep consistency in mind
  - Code consistency (maintainability)
  - Data consistency (structure, usability, breaking changes, etc.)

Given that we are striving for consistency, we need to validate some areas:

1. What is the structure of the data returned from the NBA?
    We need to lean towards the raw structure of stats data as this is the primary use case for the library. Secondly, we can look at the structure of the live data.
2. Is the structure of the data produced by the NBA consistent with the data contained within `data.py`? My guess is that it is not.

What I would hope to achieve here is a data structure that aligns with what the NBA (preferably the stats endpoint) would provide. We then use that as a foundational structure to combine the current team data and the team data you have provided.

If you can do that research, and provide updates here, we can put a more formal proposal together.

Note: we still need to have automation for maintainability and a potential understanding of the terms of use if the data is provided by a third party.

I look forward to this progressing.

**Comment by rsforbes** [comment]
The request is dormant w/o feedback being addressed.

**Pull request closed without merging**
