### PR TITLE
Live Data Endpoint on S3

### PR DESCRIPTION
**Pull request by rsforbes**
@swar - Wanted to get your input on the following PR. 

`stats.nba.com` does not appear to have live game data. I was though able to find live game data on an S3 bucket that the nba pushes to. Using your stats model for libraries, I created a `live` folder at the root next to `stats`. 

The code to use this is as follows:

```# Query for the play by play of a regular season game
from nba_api.live.endpoints import playbyplay
playbyplay.PlayByPlay('0012000048').get_dict()
```

Not sure how this should all be laid out hence my request for review. I don't need an immediate turn around as I'll be using my fork for now. I'm also not sure to the extent of the S3 bucket. It does appear that they keep a significant amount of data in there. 

Let me know your thoughts, very interested in what you think. Thanks!

### CODE REVIEW

**Comment by swar** [comment]
This looks really good @rsforbes! I can take a more in-depth look at this next week as I will have some time with a short work week.

**Comment by swar** [comment]
If you want to get this as ready as possible and then tag me, I can make any final polishes including some test cases.

**Comment by rsforbes** [comment]
Take your time. It's very rough code and needs some serious TLC. I'm very interested in your thoughts on the endpoint that I found and if there are others for live data. So pretty much the PR is more of a "hey, look what I found." :-D

I'm also curious that since the NBA is pushing this to AWS US-EAST-1 if they aren't also somehow replicating it similar to a CDN. Who knows.

**Comment by swar** [comment]
Oh! That's a very good theory as well. I wondering if we can get someone from the West Coast to try this out since we're both in the Eastern part of the Midwest. Where did you find that URL?

**Comment by rsforbes** [comment]
So AWS just released this month the ability to replicate S3 buckets to other regions so I doubt that there is any other URL at this time.

As for where I found it, I was using Chrome's dev tools and poking around at the data. Since I wasn't getting anything through the stats endpoints during the game I thought, let's check what's actually coming through. That's when I found it. It was also documented in one of their js files. I looked today and can find no reference of it. So while the playbyplay is still coming through, it must be coming from somewhere else. The LiveData url still works though.

btw. I found another one today `https://nba-prod-us-east-1-mediaops-stats.s3.amazonaws.com/NBA/liveData/scoreboard/todaysScoreboard_00.json`. Just using DevTools and searched for us-east-1. Tomorrow starts the NBA season so I'll be checking again during the games.

**Comment by rsforbes** [comment]
Spent some time looking at the web requests/data during the BKN/GSW game tonight. The links were found in a stats-json.js file

```
export const STATS_S3_URL_STATIC = `${CDN_HOST}/static/json/staticData`;
export const STATS_S3_URL_LIVE = `${CDN_HOST}/static/json/liveData`;

// generic handler for fetching stats files from S3
// https://nba-dev-us-east-1-mediaops-stats.s3.amazonaws.com/NBA/liveData/playbyplay/playbyplay_0021900959.json
// https://nba-dev-us-east-1-mediaops-stats.s3.amazonaws.com/NBA/liveData/boxscore/boxscore_0021900957.json
// https://nba-dev-us-east-1-mediaops-stats.s3.amazonaws.com/NBA/liveData/linescore/linescore_0021900957.json
```

Perhaps even better, is that the NBA is publishing this data to the Akamai Edge network so that would make it available globally. We should be using these endpoints and not S3.

```
Request URL: https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json
Request URL: https://cdn.nba.com/static/json/liveData/gameOdds/0022000001.json
Request URL: https://cdn.nba.com/static/json/liveData/boxscore/boxscore_0022000001.json
Request URL: https://cdn.nba.com/static/json/liveData/playbyplay/playbyplay_0022000001.json
```

There's also some super cool easy data to get on the cdn as they are serving images up as well as other content.
```
Example: 
nba_api/stats/library/data.py
[1627747, "LeVert", "Caris", "Caris LeVert", True] 
maps to 
https://cdn.nba.com/headshots/nba/latest/260x190/1627747.png

and same with teams and logos

[1610612744, 'GSW', 'Warriors', 1946, 'Golden State', 'Golden State Warriors', 'California']
maps to 
https://cdn.nba.com/logos/nba/1610612744/primary/L/logo.svg
```

**Comment by rsforbes** [comment]
@swar ... More data for you. This is a sample from the live boxscore endpoint. Unlike stats, the live endpoints do not contain headers, it's straight json. While some data is consistent (e.g. boxscore), others is not (playbyplay). It's not something nice and neat for something like Pandas. For JSON, absolutely. Could create some documentation around how to use it. Still think that it should live at it's own root level, outside of stats (e.g. live or live_data) since it's a totally different endpoint. Perhaps we also have a root level folder for content too. Either way, looking forward to your thoughts on this given you have setup a great structure already for the project. Planning to do some more work on this PR. Feedback more than welcome! :-)

```
{
   "meta":{
      "version":1,
      "code":200,
      "request":"http://nba.cloud/games/0022000001/boxscore?Format=json",
      "time":"2020-12-22 23:24:13.537508"
   },
   "game":{
      "gameId":"0022000001",
      "gameTimeLocal":"2020-12-22T19:00:00-05:00",
		...
      "arena":{
         "arenaId":461,
         "arenaName":"Barclays Center",
        ...},
      "officials":[
         {
            "personId":2534,
            "name":"Zach Zarba",
            "nameI":"Z. Zarba",
            "firstName":"Zach",
            "familyName":"Zarba",
            "jerseyNum":"15",
            "assignment":"OFFICIAL1"
         },...],
      "homeTeam":{
         "teamId":1610612751,
         "teamName":"Nets",
         ...
         "periods":[
            {
               "period":1,
               "periodType":"REGULAR",
               "score":40
            },...],
         "players":[
            {
               "status":"ACTIVE",
               "order":1,
               "personId":203925,
				...
               "statistics":{
                  "assists":2,
                  "blocks":1,
                  "blocksReceived":0,
                  ...},
               "name":"Joe Harris",
               "nameI":"J. Harris",
               "firstName":"Joe",
               "familyName":"Harris"
            },...}],
         "statistics":{
            "assists":24,
            "assistsTurnoverRatio":1.2,
            ...}},
      "awayTeam":{
         "teamId":1610612744,
         "teamName":"Warriors",
         "teamCity":"Golden State",
         ...
         "periods":[
            {
               "period":1,
               "periodType":"REGULAR",
               "score":25
            },...],
         "players":[
            {
               "status":"ACTIVE",
               "order":1,
               "personId":203952,
               ...
               "statistics":{
                  "assists":1,
                  "blocks":1,
                  ...},
               "name":"Andrew Wiggins",
               "nameI":"A. Wiggins",
               "firstName":"Andrew",
               "familyName":"Wiggins"
            },...],
         "statistics":{
            "assists":26,
            "assistsTurnoverRatio":1.44444444444444,
            "benchPoints":35,
            ...}}}}
```

**Comment by rsforbes** [comment]
Adding the following to this thread. Found a constants file within one of the webpacks

```
export const playByPlayEventPropTypes = PropTypes.shape({
  actionNumber: PropTypes.number,
  clock: PropTypes.string,
  timeActual: PropTypes.string,
  period: PropTypes.number,
  periodType: PropTypes.string,
  actionType: PropTypes.string,
  subType: PropTypes.string,
  qualifiers: PropTypes.arrayOf(PropTypes.string),
  personId: PropTypes.number,
  possession: PropTypes.number,
  scoreHome: PropTypes.string,
  scoreAway: PropTypes.string,
  edited: PropTypes.string,
  orderNumber: PropTypes.number,
  description: PropTypes.string,
  personIdsFilter: PropTypes.arrayOf(PropTypes.number),
  teamId: PropTypes.number,
  teamTricode: PropTypes.string,
  descriptor: PropTypes.string,
  jumpBallRecoveredName: PropTypes.string,
  jumpBallRecoverdPersonId: PropTypes.number,
  playerName: PropTypes.string,
  playerNameI: PropTypes.string,
  jumpBallWonPlayerName: PropTypes.string,
  jumpBallWonPersonId: PropTypes.number,
  jumpBallLostPlayerName: PropTypes.string,
  jumpBallLostPersonId: PropTypes.number,
  ...
```

So returning the raw json is pretty straight forward. Should people want that in some kind of data_frame I suppose is the question.

**Comment by rsforbes** [comment]
@swar - I've added fully working examples of the 4 json files in  docs/examples/PlayByPlay_Live.ipynb. That should help significantly. If you just pull the code down, you can reivew and run the Jupyter Notebook. I'm still learning on the structure of the classes so there's still much to do. :-)

**Comment by rsforbes** [comment]
@swar - Additional thought. What if you created a branch off of master, much like I did called Live, or whatever. I can push that that branch and we can collaborate on the code there. This will help protect master as we get the live data correctly coded up.

**Comment by rsforbes** [comment]
@swar - This ready for your review and merge. Couple things.

1. It's fully backward compatible
2. Tests are fully functioning
3. We should certainly cut a new minor version...this is a pretty big deal.

Test away. There's a Jupyter Notebook that walks you through how to use it.

Hope you enjoy it...as I hope everyone else does as well.

Feedback welcome for any changes you think are needed.

**Comment by OmegaP1** [comment]
@rsforbes thanks for your work, i just have a small question, how can i know from inside the API the games later tonight?

**Comment by rsforbes** [comment]
> @rsforbes thanks for your work, i just have a small question, how can i know from inside the API the games later tonight?

@OmegaP1 - You need to use the ScoreBoard.
```
# Query nba.live.endpoints.scoreboard and  list games in localTimeZone
from datetime import datetime, timezone
from dateutil import parser
from nba_api.live.nba.endpoints import scoreboard

f = "{gameId}: {awayTeam} vs. {homeTeam} @ {gameTimeLTZ}" 

board = scoreboard.ScoreBoard()
print("ScoreBoardDate: " + board.score_board_date)
games = board.games.get_dict()
for game in games:
    gameTimeLTZ = parser.parse(game["gameTimeUTC"]).replace(tzinfo=timezone.utc).astimezone(tz=None)
    print(f.format(gameId=game['gameId'], awayTeam=game['awayTeam']['teamName'], homeTeam=game['homeTeam']['teamName'], gameTimeLTZ=gameTimeLTZ))
```

**Comment by swar** [comment]
I already messaged Randy about this but this is still in the works. I need to get through a lot of bugs with the analyzer because of changes on the NBA API's website.

**Comment by drewthor** [comment]
FWIW those cdn url's appear to be the newest and most complete data surrounding stats. An older, albeit more complete with  far more endpoints and data can be found looking at the response from https://data.nba.net/prod/v1/today.json

**Pull request merged**
