### PR TITLE
Create stats scoreboardv3 endpoint

### PR DESCRIPTION
**Pull request by tmadjedi**
New endpoint for scoreboardv3 in the stats API. Response data structure is quite different from scoreboard and scoreboardv2, more similar to the live scoreboard endpoint. Day offset parameter doesn't seem to be supported.

### CODE REVIEW

**Review by rsforbes — CHANGES_REQUESTED** [review]
@tmadjedi - Thank you for the PR.

Reviewing your code, I realized that this endpoint, while under stats.nba.com, does not return data in a format that aligns with the other stats endpoints. The result is that it would break Pandas DataFrames; a key feature of the library, thus the PR cannot be accepted.

Not sure why this is, but it's interesting. I'll certainly have to note it and other similar endpoints.

It would be nice if they gave you an option to indicate the data type in the header.

Happy to discuss further.

**Comment by tmadjedi** [comment]
Ah, I see. Apologies, I probably would have caught that if I was more familiar with the library.

Do you think this endpoint belongs outside of the stats package, since the data format doesn't align with the other stats endpoints? Or perhaps it could use a new nested data set class within the stats endpoint base class?

**Comment by rsforbes** [comment]
> 

Good question. I didn't look closely at the data itself.

1. How close is the data to the live [scoreboard](https://github.com/swar/nba_api/blob/master/src/nba_api/live/nba/endpoints/scoreboard.py)?
2. Have you found other v3 endpoints?
4. Is it just historical data or is it actual live data?

**Comment by rsforbes** [comment]
@tmadjedi - let's continue the discussion on [Issue #292](https://github.com/swar/nba_api/issues/292)

**Comment by rsforbes** [comment]
@tmadjedi - FYI. It's taken longer than expected, but we're merging a V3 endpoint update today.

**Pull request closed without merging**
